# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

  encoders:
        ClienteBundle\Entity\Cliente:
            algorithm: bcrypt


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
       our_db_provider:
          entity:
              class: ClienteBundle:Cliente
              property: username


  firewalls:


        cliente:
         anonymous: ~
         pattern: ^/client
         form_login:
            login_path: /client/login
            check_path: /client/login_check
         provider: our_db_provider
         logout:
                path:   /logout
                target: /

        #cliente:
      #      pattern:    ^/cliente
      #      http_basic: ~
      #      provider: our_db_provider
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
  access_control:

        - { path: ^/cliente, role: ROLE_CLIENTE }
        - { path: ^/adminxs/servicio/, role: ROLE_ADMIN }
